### ISSUE TITLE
Request: Make Snow Golems immune to rain?

### ISSUE THREAD

**Issue by tacticalretard** [maxanier/EnhancedSnowman#2]
Would it be possible to make Snow Golems immune to rain? I like being able to use Snow Golems effectively now, but their ability to be used in biomes where it rains is very limited. I can use them normally until it starts to rain, but it only takes one sudden rainstorm to wipe out all of my Snow Golems.

**Comment by maxanier** [comment]
Added as an optional (disabled by default) config option with version 1.1 for 1.18/19
