### ISSUE TITLE
1.14.4 newest forge, crashing

### ISSUE THREAD

**Issue by Giintaras** [maxanier/EnhancedSnowman#5]
Created new world (superflat, snowy kingdom preset) and spawned some snow golems with /summon command, as soon as there were 2 of them attacking a mob, I crashed instantly.

Tried disabling mob freeze in the config; no effect.
Tried building snow golems instead of /summon. no effect.

Heres link to pastebin: https://pastebin.com/tU10xKt8

**Comment by maxanier** [comment]
Thank you for reporting, is fixed and new version is uploading right now.

Apparently I missed that this wasn't on 1.14.4 yet. Also did not expect a breaking change here.
